apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal-ingress
  namespace: hydrosim
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  tls:
    - hosts:
        - portal.hydrosim.cn
      secretName: portal-tls
  rules:
    - host: portal.hydrosim.cn
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: portal-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portal-frontend
                port:
                  number: 80
