apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal-controller-sa
  namespace: hydrosim
  labels:
    app: hydrosim-portal
    component: deployment-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: student-project-manager
  namespace: students-gd
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "patch", "update"]
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["create", "get", "list", "patch", "update"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-portal-sa-to-students-gd
  namespace: students-gd
subjects:
  - kind: ServiceAccount
    name: portal-controller-sa
    namespace: hydrosim
roleRef:
  kind: Role
  name: student-project-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: student-project-manager
  namespace: students-cd
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "patch", "update"]
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["create", "get", "list", "patch", "update"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-portal-sa-to-students-cd
  namespace: students-cd
subjects:
  - kind: ServiceAccount
    name: portal-controller-sa
    namespace: hydrosim
roleRef:
  kind: Role
  name: student-project-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portal-monitoring-read
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "namespaces"]
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portal-monitoring-read
subjects:
  - kind: ServiceAccount
    name: portal-controller-sa
    namespace: hydrosim
roleRef:
  kind: ClusterRole
  name: portal-monitoring-read
  apiGroup: rbac.authorization.k8s.io
