apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-backend
  namespace: hydrosim
  labels:
    app: portal-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-backend
  template:
    metadata:
      labels:
        app: portal-backend
    spec:
      serviceAccountName: portal-controller-sa
      containers:
        - name: portal-backend
          image: registry.hydrosim.cn/hydrosim-portal-backend:1.0.0
          imagePullPolicy: Always
          command: ["uvicorn"]
          args:
            - app.main:app
            - --host
            - 0.0.0.0
            - --port
            - "8000"
            - --proxy-headers
            - --forwarded-allow-ips
            - "*"
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: portal-backend-config
            - secretRef:
                name: portal-backend-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
