apiVersion: v1
kind: Secret
metadata:
  name: portal-backend-secret
  namespace: hydrosim
type: Opaque
stringData:
  DATABASE_URL: "postgresql://hydrosim_portal:StrongPass123@portal-postgres:5432/hydrosim_portal"
  JWT_SECRET_KEY: "b8c2f1d4e3a9c6f0f7ab12cd34ef56a790b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5"
  MINIO_ACCESS_KEY: "w2TMFAAEuIRlHTUndptR"
  MINIO_SECRET_KEY: "WmCrjVKoWG11RX5brub1RvfOtxSrqA27WWitqyDc"
  GITEA_TOKEN: "0bb0a9b7ab2073e8c6d47a29d426f11c8ed6b216"
  DEPLOY_TRIGGER_TOKEN: "change-me"
