apiVersion: v1
kind: Service
metadata:
  name: portal-backend
  namespace: hydrosim
  labels:
    app: portal-backend
spec:
  type: ClusterIP
  selector:
    app: portal-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
