apiVersion: v1
kind: Service
metadata:
  name: portal-frontend
  namespace: hydrosim
  labels:
    app: portal-frontend
spec:
  type: ClusterIP
  selector:
    app: portal-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
